# Ref_Fitter.exe : Fit_Ref.cc
# 	g++ RooParametricBinningStepFunction.cxx  -W -Wall -O2 $^ -o $@ RooParametricBinningStepFunction_cxx.so `root-config --cflags --libs` -lRooFitCore -lRooFit
Loop_Fitter.exe : Loop_fit.cc
	g++  -W -Wall -O2 $^ -o $@ `root-config --cflags --libs` -lRooFitCore -lRooFit 

